{% set version = "0.8" %}

package:
  name: pockets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pockets/pockets-{{ version }}.tar.gz
  sha256: 27c89e24010ad722c6ee0bacd9fa2f74edeb03e661925e68c4114233bf587616

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - six >=1.5.2

test:
  imports:
    - pockets

about:
  home: "http://pockets.readthedocs.org"
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: "A collection of helpful Python tools!"

extra:
  recipe-maintainers:
    - ocefpaf
