travis:
  secure:
    BINSTAR_TOKEN: Uk9az9Vh8HRjm+CHli3cCrz2du6N/oxuBKvqNKOlVyq4Y8g/v3JAEnSknKw9TFYIx4JEfk933EeQmoI25q3QlZqH5rA2Nm4SbpWUT/+h+44pvf00mtpV/8ykDugx4w4Y6Oh1nEKI4d4SNoAGIg9L3QYYfjrbtQrN1TOuM+ktx1endHw4HTIgh47ADy3+o0yDEBiXGhPaEBlNdYZV/ovnYXXbOR7W88H1IlHTJui2VxzpJNy0ixDN5XmNAswfxvY1YjhYq0mKzKRX7MHnDmKg5NnLir7r8HQyFKznmmgu4yJIbIOLSpce5hy88Rzij9fMJ0Ieob5XhYqBmborJiBd4TGYcZnnww2xxKAnG1ayy8/gDYz+nDzXutTvDCsR9zAS3klF0B/FDbszvW26Yn0WI22h2Nfv6VY1r9TSecKHh4/ayYcNBD+kb4ey+22OyoTgFFLRIcIj/8W1V4L1ggpHLa78jh4igXVzX/nB92HkV2ATun2q3CjCa5+601K73i5rGOROg+/WqpXzN2XmSGjleevf6GtaISoARIqVLtEVgfk/e+xgqfyA2V8x4lcfBbMlWQqSvzJn5ovo160hkIpXyWFdhsKXDh5hpFDqxa4EmPV8vJU7cFIH1Ic2Zwv05whw/E+81fCuiA7yWl3hgW/kwZl7PAqlS0IHGOv7ag8yXN4=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
